### ISSUE TITLE
Low-overhead version for use in other code

### ISSUE THREAD

**Issue by beroe** [ManrajGrover/halo#11]
This is a really slick implementation. Congrats. 

It is pretty trivial to use `pip`, but It would be great if there was a bare-bones version that we could embed or import into existing code, w/o requiring the user to install any other libraries. 

What is the minimum set needed?

**Comment by ManrajGrover** [comment]
Hi @beroe,

Thank you for your kind words. I didn't quite get it when you're saying `bare-bones version`. If you want to implement one, you can write a basic spinner (something like https://stackoverflow.com/a/4995896/2692667) where you don't need to add more dependencies to your project.

**Comment by beroe** [comment]
Yes, that simple solution is probably what I would need. Thanks for the pointer.
