### ISSUE TITLE
Discussion: `cursor` changed license

### ISSUE THREAD

**Issue by PatrikKopkan** [manrajgrover/halo#118]
Cursor is now under GPL license. Which means you should either change license too or stop using Cursor

**Comment by PatrikKopkan** [comment]
https://github.com/GijsTimmers/cursor/blob/master/LICENSE

**Comment by PatrikKopkan** [comment]
Or dont use newer versions of cursor in your project.

**Comment by PatrikKopkan** [comment]
> Or dont use newer versions of cursor in your project.

But I am no lawyer so dont rely on that much

**Comment by manrajgrover** [comment]
Thanks for bringing this up and making me aware of this. I don't get into licensing much and hence `MIT` everything, thus don't know implications of this. I will investigate this and get back.

Thanks again!

**Comment by norweeg** [comment]
@PatrikKopkan, @manrajgrover is neither changing nor distributing the source code of cursor, it is merely a a dependency.  The MIT License is also [compatible with the GPL anyway](https://en.wikipedia.org/wiki/MIT_License) anyway

**Comment by makkus** [comment]
@norweeg , not sure what you are trying to say, but being compatible only goes in one direction. If you have a GPL project, you can call MIT-licensed code. But not vice versa. So, in the case of halo, you are not allowed to distribute any software that is incorporating halo (which comes with cursor) unless you license your software GPL.

I'd suggest to at least freeze the cursor dependency to version 1.2.0 (the last non-GPL version). Or use something like [vistir](https://github.com/sarugaku/vistir#-cursor-utilities), which unfortunately is a bit heavier, but comes in quite handy in a lot of cases. I'm using vistir in my project anyway, so ideally (for me) would be if halo would be happy with either one of the dependencies. Either way, currently, I would strongly recommend you specify 'cursor==1.2.0' in the dependency list of your own (non-GPL) project if you are using halo...

**Comment by makkus** [comment]
@norweeg have you actually read: https://www.gnu.org/licenses/gpl-faq.en.html#WhatDoesCompatMean ?

It explicitely states: 

All GNU GPL versions permit such combinations privately; they also permit distribution of such combinations provided the combination **is released under the same GNU GPL version**. The other license is compatible with the GPL if it permits this too. [emphasis mine]

There are a lot of questions regarding this on stackoverflow and such, e.g.:

https://stackoverflow.com/questions/11819831/including-gpl-external-library-in-mit-code
https://opensource.stackexchange.com/questions/6062/using-gpl-library-with-mit-licensed-code

As long as you don't distribute the resulting work (your non-GPL'ed software), you're fine. But as soon as you want to distribute, you'll have to change the license of your code to GPL.

**Comment by makkus** [comment]
>  If you, however, created software using halo (and therefore also cursor), packaging both modules with it (e.g. with PyInstaller) and distribute that or otherwise included the cursor codebase in your code, you would be bound by the terms of the GPL, as that is a derivative work.

I guess we agree then, that is the only relevant point I wanted to make. Of course 'halo' itself is safe. But, in practice, I can't see how that matters. 'halo' itself will never be distributed on it's own, it'll always be used as part of a larger application, as it's a library, not an application. So, its utility depends on being able to use it in your own application. As long as that is GPL, there is no problem. But if not, then halo might as well GPL'ed itself, because I could not use it in my MIT-licensed application. In which way do you think halo useful on it's own?

**Comment by takeda** [comment]
@manrajgrover all you need to do is to call `stdout.write("\033[?25l")` to hide a cursor and `stdout.write("\033[?25h")` to show it, there's no need to add this package so it can hijack the license.

Please remove this dependency, not only it makes your code "heavier", someone who incorporates your code into theirs might run into legal issues.

**Comment by manrajgrover** [comment]
@PatrikKopkan @makkus @norweeg Thank you so much for insightful discussion! :) 

I've removed `halo`'s dependency on `cursor` and have directly used a StackOverflow response on which that repo was based. This resolves this issue.

I'm also sorry for such delayed response. Recent events have kept me busy. Hence, I'm actually looking for maintainers of this project. If you're interested, feel free to drop an email regarding this. Thanks again!

**Comment by manrajgrover** [comment]
I've made the release in `v0.0.30`

**Comment by norweeg** [comment]
I'm always free to help in my spare time.  I'll try to resolve some bugs.  also I must apologize I have not been good at keeping up with the PRs I made a few months ago.  I'll rebase them on main and come up with some tests.  I have a few ideas how Halo might be improved as well which I may PR in the near future
