### ISSUE TITLE
Debug log on terminal

### ISSUE THREAD

**Issue by antoiner77** [ManrajGrover/halo#14]
Hi,
when using Halo with boto3, I have a strange behaviour, all the debug log from boto are displayed 
![capture d ecran 2017-10-03 a 15 19 27](https://user-images.githubusercontent.com/10193614/31127135-485d24ec-a84e-11e7-9584-a5a37ea5190d.png)
MacOS/Python3.6
halo (0.0.5)
boto3 (1.4.4)

Thanks

**Comment by lchabert** [comment]
Hi,

I have the same behaviour when using halo and openstacksdk on python 2.7.

Regards.

**Comment by tizz98** [comment]
@ManrajGrover I can work on this one. I think the solution here is to just create a logger specific for `halo` rather than removing logging altogether as was done in #18

**Comment by JungWinter** [comment]
It looks like solved in #12. @ManrajGrover right?

**Comment by ManrajGrover** [comment]
@JungWinter Yes, I'm waiting for final changes before merging. :)
