### ISSUE TITLE
Spinner does not animate during some external function call.

### ISSUE THREAD

**Issue by digital-idiot** [manrajgrover/halo#170]
## Description
Spinner does not animate during external function call.

### System settings

- Operating System: `Linux 5.16.11-2`
- Terminal in use: `Bash`
- Python version: `3.9.6`
- Halo version: `0.0.30`

### Error
There is no error message, just the spinner animation is stuck at initial position the entire time.
 
### Expected behaviour
There spinner should animate normally

## Steps to recreate

Below is a sample code to reproduce the error:
```python
import json, pdal
from halo import Halo

rt = [
    {
        "type": "readers.las",
        "filename": "Test.las"
    }
]
p = pdal.Pipeline(json.dumps(rt))

with Halo(text='Loading', spinner='dots'):
    p.execute() # Spinner does not animate during this
```
## People to notify
@manrajgrover

**Comment by shahriyardx** [comment]
This is because the function is blocking
