### ISSUE TITLE
BUG: Halo.__init__.<locals>.clean_up() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by guigoruiz1** [manrajgrover/halo#179]
## Description
Using `ipython>8.16.1`, every jupyter notebook cell containing a Halo spinner returns the error `Halo.__init__.<locals>.clean_up() takes 0 positional arguments but 1 was given`. Apparently the newer versions of ipython are returning an argument to the `clean_up()` method.

[This pull request](https://github.com/ipython/ipython/pull/14216/commits/1a8be18f09292c103d55474a5b7eac51e3895fb1) seems to be the culprit.

### System settings

- Operating System: MacOS and Ubuntu
- Terminal in use: ?
- Python version: 3.11.6
- Halo version: latest
- `pip freeze` output:
```
aiohttp==3.8.6
aiosignal==1.3.1
appnope==0.1.3
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.1.0
backcall==0.2.0
certifi==2023.7.22
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.1.4
contourpy==1.2.0
cycler==0.12.1
debugpy==1.8.0
decorator==5.1.1
discord.py==2.3.2
entrypoints==0.4
executing==2.0.1
fastjsonschema==2.18.1
fonttools==4.44.0
frozenlist==1.4.0
gevent==23.9.1
gitdb==4.0.11
GitPython==3.1.40
greenlet==3.0.1
halo==0.0.31
idna==3.4
ipykernel==6.26.0
ipylab==1.0.0
ipython==8.17.2
ipywidgets==8.1.1
itables==1.6.2
jedi==0.19.1
jsonschema==4.19.2
jsonschema-specifications==2023.7.1
jupyter_client==8.6.0
jupyter_core==5.5.0
jupyterlab-widgets==3.0.9
kiwisolver==1.4.5
log-symbols==0.0.14
matplotlib==3.8.1
matplotlib-inline==0.1.6
matplotlib-venn==0.11.9
multidict==6.0.4
nbclient==0.9.0
nbformat==5.9.2
nbstripout==0.6.1
nest-asyncio==1.5.8
numpy==1.26.1
packaging==23.1
pandas==2.1.2
papermill==2.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.1.0
platformdirs==3.11.0
prompt-toolkit==3.0.39
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
PyNaCl==1.5.0
pyparsing==3.1.1
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
PyYAML==6.0.1
pyzmq==25.1.1
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rpds-py==0.12.0
scipy==1.11.3
seaborn==0.13.0
six==1.16.0
smmap==5.0.1
spinners==0.0.24
stack-data==0.6.3
tenacity==8.2.3
termcolor==2.3.0
tornado==6.3.3
tqdm==4.66.1
traitlets==5.13.0
tzdata==2023.3
urllib3==2.0.7
wcwidth==0.2.9
widgetsnbextension==4.0.9
wikitextparser==0.55.4
yarl==1.9.2
zope.event==5.0
zope.interface==6.1
```

### Error
`Halo.__init__.<locals>.clean_up() takes 0 positional arguments but 1 was given`
 
### Expected behaviour
Halo clean_up() method should accept an argument.

## Steps to recreate
Upgrade ipython to the latest version

## People to notify
@manrajgrover

**Comment by anand-kamble** [comment]
Any updates on this issue? I am getting the same error with IPython v8.24.0.

**Comment by manrajgrover** [comment]
Thank you for reporting the issue, and my sincere apologies for the delay. The project requires a lot of housekeeping, given a lot has changed in terms of the latest Python releases and CI/CD changes. The fix for this issue has been merged and a release will be made soon.

**Comment by galenhwang** [comment]
@manrajgrover what's the priority of another `halo` release? this issue still remains unresolved and i would reopen this issue

* (repeated from https://github.com/manrajgrover/halo/pull/180#issuecomment-2327362516)
