### ISSUE TITLE
__init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by fuuman** [ManrajGrover/halo#19]
I've just wanted to try out your example and got the following error. 

`TypeError: __init__() got an unexpected keyword argument 'text'`

Installed halo via pip.

**Comment by JungWinter** [comment]
Version of halo using pip to install is `0.0.5`. So it doesn't support `__init__` using keyword argument like `Halo(text='Loading', spinner='dots')` yet. Try `Halo({'text':'Loading', 'spinner':'dots'})`

**Comment by ManrajGrover** [comment]
@fuuman This should have been fixed now. Please set version `0.0.6` while reinstalling. Let me know if you are facing any issue.

**Comment by ManrajGrover** [comment]
@fuuman Closing this. Let me know if you're still facing this issue and I'll reopen this.
