### ISSUE TITLE
Push README to Pypi

### ISSUE THREAD

**Issue by manrajgrover** [manrajgrover/halo#31]
Currently, README is in markdown which is not supported by pypi. We need to convert the file to reStructuredText for `pypi`. This can be automated.

**Comment by niloch** [comment]
I've used [setuptools-markdown](https://github.com/msabramo/setuptools-markdown) in other projects, but you have to check the output to make sure it will render correctly on pypi which is fairly strict.

**Comment by PritishSehzpaul** [comment]
Hi, can you explain to me what is to be done? I will like to help. 
As far as I understand we can use Markdown for uploading to pypi, according to: https://packaging.python.org/guides/making-a-pypi-friendly-readme/

**Comment by manrajgrover** [comment]
@PritishSehzpaul Yes, it seems that now it supports markdown. We still don't push markdown to Pypi. This seems like an easy fix. Changing the issue title. Feel free to pick it up and send a PR.

@niloch My apologies. I missed your previous comments. Thank you so much for your involvement!
