### ISSUE TITLE
Text in front of spinner

### ISSUE THREAD

**Issue by tvdsluijs** [ManrajGrover/halo#56]
Not a real bug but a feature request.

It would be great if the Text could be in front of the spinner.

I created my own frames which gives me

. Loading
.. Loading
... Loading
..... Loading
...... Loading
....... Loading
...... Loading
..... Loading
.... Loading
... Loading
.. Loading
. Loading

:-) but I would like Loading in front (and keep loading as a text 👍 )

**Comment by ManrajGrover** [comment]
Hi @tvdsluijs, looks like this feature is in demand and I guess there is already a PR for it (#52). The only reason that PR is being held upon is I cannot think of a reason to add this feature. Maybe if you could share a use case for it, I can think more. Also, let me know if #52 is resolving this or I'm not understanding your feature request.

**Comment by mverteuil** [comment]
@ManrajGrover Perhaps you could consider using an enumeration controlled `placement` argument which defaults to the original placement? I think a spinner/progress indicator with a text prefix is a fairly common pattern. `pip` is one example of this. 

Consider that these two support this mode as well:
 - https://pypi.python.org/pypi/progress
 - https://github.com/tqdm/tqdm

**Comment by ManrajGrover** [comment]
Hi @mverteuil, thank you for sharing your thoughts.

> Perhaps you could consider using an enumeration controlled placement argument which defaults to the original placement

I didn't quite get this.

>  I think a spinner/progress indicator with a text prefix is a fairly common pattern. pip is one example of this.
> 
> Consider that these two support this mode as well:
>
> https://pypi.python.org/pypi/progress
> https://github.com/tqdm/tqdm

This makes sense. But should one expect user to provide a custom progress bar? One reason for this being different from tqdm is tqdm focuses more on iterative tasks while this library focuses on async tasks. I can add support for iterative tasks with this feature but I would keep it at spinners and not progress bars.

Would you check if #52 is serving the feature request?

**Comment by mverteuil** [comment]
> Perhaps you could consider using an enumeration controlled placement argument which defaults to the original placement

This comment is grounded in the implementation that exists in #52. For example, instead of using `right=False`, you could use `placement=Placement.LEFT`. This allows more flexibility and makes having multiple options be mutually exclusive down the road easier. I may be overreaching a bit with that concern. I think that PR is a good start, but my issue lies in the signature.

I agree with you about keeping it spinners, as there are other projects that support progress bars already. I was more trying to indicate that those projects have some flexibility in labelling the progress.

**Comment by ManrajGrover** [comment]
@mverteuil We can work through the signature. Providing `Placement` enum is a good idea but I'm not sure if it's an overkill. I don't see any other positions where spinner can be placed (other than left or right). But yeah, we can surely have `placement` keyword argument and have default string as `'right'`.

**Comment by ManrajGrover** [comment]
This feature has been added in #57. This will be made available in next release. 😄 Thanks to @stephen-bunn 🙌
