### ISSUE TITLE
Bug: placement='right' in API doesn't work

### ISSUE THREAD

**Issue by hshong9590** [ManrajGrover/halo#65]
## Description
After adding ```placement='right'``` in the Halo constructor, the code gives an error that says "TypeError: __init__() got an unexpected keyword argument 'placement'".
Am I doing something wrong here?

```
from halo import Halo
import time

spinner = Halo(text='Loading', spinner='dots', placement='right')
spinner.start()

time.sleep(3)  # Running time-consuming work

spinner.stop()
```

### System settings

- Operating System: macOS
- Terminal in use: iTerm2
- Python version: 3.65
- Halo version: 0.0.12
- `pip freeze` output:
backports.shutil-get-terminal-size==1.0.0
colorama==0.3.9
cursor==1.2.0
enum34==1.1.6
halo==0.0.12
log-symbols==0.0.11
six==1.11.0
spinners==0.0.19
termcolor==1.1.0

### Error
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    spinner = Halo(text='Loading', spinner='dots', placement='right')
TypeError: __init__() got an unexpected keyword argument 'placement'
 
### Expected behaviour
The spinner should be placed on the right of text.

**Comment by ManrajGrover** [comment]
Hi @hshong9590 ,

Thanks for opening this issue. I believe this is happening because this feature is not released for now. I plan to make a release this week sometime. Can you check if you're facing this issue from master branch of this project?

**Comment by ManrajGrover** [comment]
I've made a release with this feature. Please upgrade your version to `0.0.13` and see if it is fixed. Do let me know if you're still facing this issue.

**Comment by hshong9590** [comment]
It works!
Thank you, @ManrajGrover :+1:

**Comment by ManrajGrover** [comment]
Thanks for confirming @hshong9590. Closing this.
