### ISSUE TITLE
IPython dependency should be optional

### ISSUE THREAD

**Issue by vmalloc** [ManrajGrover/halo#67]
halo currently *requires* IPython 5.x, meaning that project depending on it cannot use newer versions.

Logically I don't think it makes much sense because there are many uses to halo not involving IPython at all, meaning this dependency should be optional (i.e. `extras`)

**Comment by ManrajGrover** [comment]
Hi @vmalloc,

Thanks for opening this issue. Agreed, it should depend on the environment. Would you like to open a PR for it?
