### ISSUE TITLE
Version 3 support

### ISSUE THREAD

**Issue by AmirZero** [ManrajGrover/halo#7]
Currently halo only supports version 2.
That'll be nice if we add version 3 support for halo.\
Best of luck.

**Comment by ManrajGrover** [comment]
Hi Amir, I believe Python 3 is already supported. I've tested it as well (see https://travis-ci.org/ManrajGrover/halo). Please let me know if you're facing any issue using the library on Python 3.

**Comment by strattner** [comment]
@AmirZero I installed this through pip, and found it doesn't work in Python 3, but if you grab the latest version (git clone ... ) it works.

For example:

```
from halo import Halo
import time
spinner = Halo(text='Loading', spinner='dots')
spinner.start()
i = 0
while i < 100:
    i = i + 1
    time.sleep(1)
spinner.stop()
```
using the pip version:
$ python3 spin.py 
Traceback (most recent call last):
  File "spin.py", line 3, in <module>
    spinner = Halo(text='Loading', spinner='dots')
TypeError: __init__() got an unexpected keyword argument 'text'

using latest version:
$ python3 spin.py 
⠦ Loading

**Comment by JungWinter** [comment]
@strattner  Version of halo using pip to install is `0.0.5`. So it doesn't support `__init__` using keyword argument like `Halo(text='Loading', spinner='dots')`. Anyway, pip version is working in Python 3 :)

**Comment by ManrajGrover** [comment]
@strattner This should have been fixed now. Please reinstall the package and set version as `0.0.6`. Let me know if you are still facing any issue.

**Comment by strattner** [comment]
@ManrajGrover looks good, thanks

**Comment by massenz** [comment]
FWIW I just installed via pip and works great under Python 3.5.2 --  :heart: this project!
@ManrajGrover thanks for creating and sharing this, you're a :star2:

**Comment by ManrajGrover** [comment]
@massenz @strattner Thank you for confirming. ❤️ 

@JungWinter Thank you for helping in handling some of the issues. ❤️ 

@massenz Thank you for your kind words! 😄 

Closing this issue!
