### ISSUE TITLE
Bug found on initializing text attribute

### ISSUE THREAD

**Issue by AmirZero** [ManrajGrover/halo#8]
I  found a bug, when you try to use "\n" escape in "text" attribute when you want to initialize your Halo object at first.

Just try Defining a Halo object like this 

`spinner = spinner = Halo({'text': 'Loading \n', 'spinner': 'dots'})`
and then if you start it, its like you put it in a while loop and then start.

**Comment by ManrajGrover** [comment]
Accepted. We should strip line endings from text before rendering it.
