### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by manrajgrover** [manrajgrover/halo#88]
## Description
Currently, the test coverage is around 88% which is okay but we can improve it. This issue focuses on adding tests covering missing branches.

## People to notify
@manrajgrover

**Comment by Lilja** [comment]
I'm interested!

**Comment by manrajgrover** [comment]
@Lilja Go ahead! Do let me know if you need any assistance.

**Comment by Lilja** [comment]
Status report: Trying out the bounce animation, but i'm not sure if I discovered a bug or not.

```python3
text = "{}abc".format("_" * 80)
spinner = Halo(text, animation="bounce")
print(text.__len__())
spinner.start()
time.sleep(4)
spinner.stop()
```
Output(frames):

```
- ______________________________________________________________________________
\ ______________________________________________________________________________
| ______________________________________________________________________________
/ _____________________________________________________________________________a
- ____________________________________________________________________________ab
\ ____________________________________________________________________________ab
| _____________________________________________________________________________a
/ ______________________________________________________________________________
```
Shouldn't there be a C somewhere?
Win10, python 3.6.4

**Comment by Lilja** [comment]
Offsetting the range by +1 fixes it.
https://github.com/manrajgrover/halo/blob/0767ac1d6e827cbe53347d9141eb3667b7b61019/halo/halo.py#L280

**Comment by Lilja** [comment]
@manrajgrover Sure thing
